/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CategoryDto } from './category-dto';
 /**
 * 
 *
 * @export
 * @interface CategoryDto
 */
export interface CategoryDto {

    /**
     * @type {string}
     * @memberof CategoryDto
     */
    id: string;

    /**
     * @type {Date}
     * @memberof CategoryDto
     */
    createdAt: Date;

    /**
     * @type {Date}
     * @memberof CategoryDto
     */
    updatedAt: Date;

    /**
     * @type {string}
     * @memberof CategoryDto
     */
    title: string;

    /**
     * @type {string}
     * @memberof CategoryDto
     */
    icon: string;

    /**
     * @type {string}
     * @memberof CategoryDto
     */
    parentId?: string;

    /**
     * @type {Array<CategoryDto>}
     * @memberof CategoryDto
     */
    children: Array<CategoryDto>;

    /**
     * @type {CategoryDto}
     * @memberof CategoryDto
     */
    parent: CategoryDto;

    /**
     * @type {Date}
     * @memberof CategoryDto
     */
    deletedAt?: Date;
}
