/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface CategoryListDto
 */
export interface CategoryListDto {
  /**
   * @type {string}
   * @memberof CategoryListDto
   */
  id: string;

  /**
   * @type {string}
   * @memberof CategoryListDto
   */
  title: string;

  /**
   * @type {string}
   * @memberof CategoryListDto
   */
  icon: string;

  /**
   * @type {Array<CategoryListDto>}
   * @memberof CategoryListDto
   */
  children: Array<CategoryListDto>;

  /**
   * @type {CategoryListDto}
   * @memberof CategoryListDto
   */
  parent: CategoryListDto;
}
