/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ProductDto } from './product-dto';
import { UserDto } from './user-dto';
/**
 *
 *
 * @export
 * @interface CommentDto
 */
export interface CommentDto {
  /**
   * @type {string}
   * @memberof CommentDto
   */
  id: string;

  /**
   * @type {Date}
   * @memberof CommentDto
   */
  createdAt: Date;

  /**
   * @type {Date}
   * @memberof CommentDto
   */
  updatedAt: Date;

  /**
   * @type {ProductDto}
   * @memberof CommentDto
   */
  product: ProductDto;

  /**
   * @type {CommentDto}
   * @memberof CommentDto
   */
  replyTo: CommentDto;

  /**
   * @type {UserDto}
   * @memberof CommentDto
   */
  user: UserDto;

  /**
   * @type {string}
   * @memberof CommentDto
   */
  text: string;

  /**
   * @type {string}
   * @memberof CommentDto
   */
  productId: string;

  /**
   * @type {string}
   * @memberof CommentDto
   */
  userId: string;

  /**
   * @type {string}
   * @memberof CommentDto
   */
  replyToId: string;

  /**
   * @type {Date}
   * @memberof CommentDto
   */
  deletedAt?: Date;
}
