/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateAddressDto
 */
export interface CreateAddressDto {

    /**
     * @type {string}
     * @memberof CreateAddressDto
     */
    title: string;

    /**
     * @type {string}
     * @memberof CreateAddressDto
     */
    address: string;

    /**
     * @type {string}
     * @memberof CreateAddressDto
     */
    floor: string;

    /**
     * @type {string}
     * @memberof CreateAddressDto
     */
    plaque: string;

    /**
     * @type {string}
     * @memberof CreateAddressDto
     */
    postalCode: string;

    /**
     * @type {string}
     * @memberof CreateAddressDto
     */
    cityId: string;
}
