/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateOrderDto
 */
export interface CreateOrderDto {

    /**
     * @type {string}
     * @memberof CreateOrderDto
     */
    coupon?: string;

    /**
     * @type {string}
     * @memberof CreateOrderDto
     */
    description?: string;

    /**
     * @type {string}
     * @memberof CreateOrderDto
     */
    addressId: string;
}
