/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateTicketChatDto
 */
export interface CreateTicketChatDto {

    /**
     * @type {Blob}
     * @memberof CreateTicketChatDto
     */
    logo?: Blob;

    /**
     * @type {string}
     * @memberof CreateTicketChatDto
     */
    ticketId?: string;

    /**
     * @type {string}
     * @memberof CreateTicketChatDto
     */
    title?: string;

    /**
     * @type {string}
     * @memberof CreateTicketChatDto
     */
    text: string;

    /**
     * @type {string}
     * @memberof CreateTicketChatDto
     */
    userToId: string;
}
