/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface CreateOrUpdateGeneralsDto
 */
export interface CreateOrUpdateGeneralsDto {
  /**
   * @type {string}
   * @memberof CreateOrUpdateGeneralsDto
   */
  address: string;
  /**
   * @type {string}
   * @memberof CreateOrUpdateGeneralsDto
   */
  telephone1: string;
  /**
   * @type {string}
   * @memberof CreateOrUpdateGeneralsDto
   */
  telephone2: string;
  /**
   * @type {string}
   * @memberof CreateOrUpdateGeneralsDto
   */
  telegram: string;
  /**
   * @type {string}
   * @memberof CreateOrUpdateGeneralsDto
   */
  instagram: string;
  /**
   * @type {string}
   * @memberof CreateOrUpdateGeneralsDto
   */
  siteAddress: string;
}
