/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateSliderDto
 */
export interface CreateSliderDto {

    /**
     * @type {string}
     * @memberof CreateSliderDto
     */
    title: string;

    /**
     * @type {string}
     * @memberof CreateSliderDto
     */
    description: string;

    /**
     * @type {string}
     * @memberof CreateSliderDto
     */
    alt: string;

    /**
     * @type {string}
     * @memberof CreateSliderDto
     */
    type: CreateSliderDtoTypeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum CreateSliderDtoTypeEnum {
    SLIDER = 'SLIDER',
    SQUARE = 'SQUARE',
    WIDE = 'WIDE'
}

