/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateSettingAdminDto
 */
export interface CreateSettingAdminDto {

    /**
     * @type {string}
     * @memberof CreateSettingAdminDto
     */
    key: string;

    /**
     * @type {any}
     * @memberof CreateSettingAdminDto
     */
    value: any;
}
