/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SupplierDto } from './supplier-dto';
import { UserDto } from './user-dto';
import { VendorDto } from './vendor-dto';
 /**
 * 
 *
 * @export
 * @interface FavoriteDto
 */
export interface FavoriteDto {

    /**
     * @type {string}
     * @memberof FavoriteDto
     */
    id: string;

    /**
     * @type {Date}
     * @memberof FavoriteDto
     */
    createdAt: Date;

    /**
     * @type {Date}
     * @memberof FavoriteDto
     */
    updatedAt: Date;

    /**
     * @type {string}
     * @memberof FavoriteDto
     */
    title?: string | null;

    /**
     * @type {string}
     * @memberof FavoriteDto
     */
    address?: string | null;

    /**
     * @type {string}
     * @memberof FavoriteDto
     */
    userId?: string;

    /**
     * @type {string}
     * @memberof FavoriteDto
     */
    vendorId?: string;

    /**
     * @type {string}
     * @memberof FavoriteDto
     */
    supplierId?: string;

    /**
     * @type {UserDto}
     * @memberof FavoriteDto
     */
    user?: UserDto;

    /**
     * @type {VendorDto}
     * @memberof FavoriteDto
     */
    vendor?: VendorDto;

    /**
     * @type {SupplierDto}
     * @memberof FavoriteDto
     */
    supplier?: SupplierDto;

    /**
     * @type {Date}
     * @memberof FavoriteDto
     */
    deletedAt?: Date;
}
