/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface LogDto
 */
export interface LogDto {

    /**
     * @type {string}
     * @memberof LogDto
     */
    id: string;

    /**
     * @type {Date}
     * @memberof LogDto
     */
    createdAt: Date;

    /**
     * @type {Date}
     * @memberof LogDto
     */
    updatedAt: Date;

    /**
     * @type {string}
     * @memberof LogDto
     */
    path?: string;

    /**
     * @type {string}
     * @memberof LogDto
     */
    userId?: string;

    /**
     * @type {string}
     * @memberof LogDto
     */
    method?: string;

    /**
     * @type {string}
     * @memberof LogDto
     */
    action?: string;

    /**
     * @type {string}
     * @memberof LogDto
     */
    userAgent?: string;

    /**
     * @type {string}
     * @memberof LogDto
     */
    ip?: string;
}
