/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TokenPayloadDto } from './token-payload-dto';
import { UserDto } from './user-dto';
 /**
 * 
 *
 * @export
 * @interface LoginPayloadDto
 */
export interface LoginPayloadDto {

    /**
     * @type {UserDto}
     * @memberof LoginPayloadDto
     */
    user: UserDto;

    /**
     * @type {TokenPayloadDto}
     * @memberof LoginPayloadDto
     */
    token: TokenPayloadDto;

    /**
     * @type {boolean}
     * @memberof LoginPayloadDto
     */
    isRegister: boolean;
}
