/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AddressDto } from './address-dto';
import { UserDto } from './user-dto';
import { VendorOrderDto } from './vendor-order-dto';
import { VendorProductDto } from './vendor-product-dto';
 /**
 * 
 *
 * @export
 * @interface OrderDto
 */
export interface OrderDto {

    /**
     * @type {string}
     * @memberof OrderDto
     */
    id: string;

    /**
     * @type {Date}
     * @memberof OrderDto
     */
    createdAt: Date;

    /**
     * @type {Date}
     * @memberof OrderDto
     */
    updatedAt: Date;

    /**
     * @type {string}
     * @memberof OrderDto
     */
    status: OrderDtoStatusEnum;

    /**
     * @type {Array<VendorProductDto>}
     * @memberof OrderDto
     */
    products: Array<VendorProductDto>;

    /**
     * @type {AddressDto}
     * @memberof OrderDto
     */
    address?: AddressDto;

    /**
     * @type {UserDto}
     * @memberof OrderDto
     */
    user?: UserDto;

    /**
     * @type {Array<VendorOrderDto>}
     * @memberof OrderDto
     */
    vendorOrders?: Array<VendorOrderDto>;

    /**
     * @type {number}
     * @memberof OrderDto
     */
    totalPrice: number;

    /**
     * @type {string}
     * @memberof OrderDto
     */
    coupon?: string;

    /**
     * @type {string}
     * @memberof OrderDto
     */
    description?: string;

    /**
     * @type {string}
     * @memberof OrderDto
     */
    addressId: string;

    /**
     * @type {number}
     * @memberof OrderDto
     */
    commission: number;

    /**
     * @type {string}
     * @memberof OrderDto
     */
    code: string;

    /**
     * @type {string}
     * @memberof OrderDto
     */
    postTrackingNumber: string;

    /**
     * @type {Date}
     * @memberof OrderDto
     */
    deletedAt?: Date;
}

/**
 * @export
 * @enum {string}
 */
export enum OrderDtoStatusEnum {
    PENDING = 'PENDING',
    PAID = 'PAID',
    ACCEPTED = 'ACCEPTED',
    SENT = 'SENT',
    DELIVERED = 'DELIVERED',
    CANCELED = 'CANCELED'
}

