/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PageMetaDto } from './page-meta-dto';
/**
 *
 *
 * @export
 * @interface PageDto
 */
export interface PageDto {
  /**
   * @type {Array<Array>}
   * @memberof PageDto
   */
  data: Array<unknown>;

  /**
   * @type {PageMetaDto}
   * @memberof PageDto
   */
  meta: PageMetaDto;
}
