/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CategoryDto } from './category-dto';
import { ProductDto } from './product-dto';
 /**
 * 
 *
 * @export
 * @interface ProductCategoryDto
 */
export interface ProductCategoryDto {

    /**
     * @type {string}
     * @memberof ProductCategoryDto
     */
    id: string;

    /**
     * @type {Date}
     * @memberof ProductCategoryDto
     */
    createdAt: Date;

    /**
     * @type {Date}
     * @memberof ProductCategoryDto
     */
    updatedAt: Date;

    /**
     * @type {ProductDto}
     * @memberof ProductCategoryDto
     */
    product?: ProductDto;

    /**
     * @type {CategoryDto}
     * @memberof ProductCategoryDto
     */
    category?: CategoryDto;

    /**
     * @type {string}
     * @memberof ProductCategoryDto
     */
    productId: string;

    /**
     * @type {string}
     * @memberof ProductCategoryDto
     */
    categoryId: string;

    /**
     * @type {Date}
     * @memberof ProductCategoryDto
     */
    deletedAt?: Date;
}
