/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ShipmentInfoDto } from './shipment-info-dto';
 /**
 * 
 *
 * @export
 * @interface ProductAttributeDto
 */
export interface ProductAttributeDto {

    /**
     * @type {string}
     * @memberof ProductAttributeDto
     */
    id: string;

    /**
     * @type {Date}
     * @memberof ProductAttributeDto
     */
    createdAt: Date;

    /**
     * @type {Date}
     * @memberof ProductAttributeDto
     */
    updatedAt: Date;

    /**
     * @type {ShipmentInfoDto}
     * @memberof ProductAttributeDto
     */
    shipmentInfo?: ShipmentInfoDto;

    /**
     * @type {string}
     * @memberof ProductAttributeDto
     */
    summery?: string;

    /**
     * @type {number}
     * @memberof ProductAttributeDto
     */
    weight?: number;

    /**
     * @type {string}
     * @memberof ProductAttributeDto
     */
    dimensions?: string;

    /**
     * @type {Array<any>}
     * @memberof ProductAttributeDto
     */
    features?: Array<any>;

    /**
     * @type {Array<string>}
     * @memberof ProductAttributeDto
     */
    colors: Array<string>;

    /**
     * @type {Date}
     * @memberof ProductAttributeDto
     */
    deletedAt?: Date;
}
