/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CategoryDto } from './category-dto';
 /**
 * 
 *
 * @export
 * @interface ProductRequestDto
 */
export interface ProductRequestDto {

    /**
     * @type {string}
     * @memberof ProductRequestDto
     */
    id: string;

    /**
     * @type {Date}
     * @memberof ProductRequestDto
     */
    createdAt: Date;

    /**
     * @type {Date}
     * @memberof ProductRequestDto
     */
    updatedAt: Date;

    /**
     * @type {CategoryDto}
     * @memberof ProductRequestDto
     */
    category: CategoryDto;

    /**
     * @type {string}
     * @memberof ProductRequestDto
     */
    title: string;

    /**
     * @type {string}
     * @memberof ProductRequestDto
     */
    description: string;

    /**
     * @type {string}
     * @memberof ProductRequestDto
     */
    media: string;

    /**
     * @type {string}
     * @memberof ProductRequestDto
     */
    categoryId: string;

    /**
     * @type {Date}
     * @memberof ProductRequestDto
     */
    deletedAt?: Date;
}
