/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { UserDto } from './user-dto';
 /**
 * 
 *
 * @export
 * @interface ProfilePayloadDto
 */
export interface ProfilePayloadDto {

    /**
     * @type {UserDto}
     * @memberof ProfilePayloadDto
     */
    user: UserDto;

    /**
     * @type {number}
     * @memberof ProfilePayloadDto
     */
    completedOrders: number;

    /**
     * @type {number}
     * @memberof ProfilePayloadDto
     */
    otherOrders: number;
}
