/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CityDto } from './city-dto';
 /**
 * 
 *
 * @export
 * @interface ProvinceDto
 */
export interface ProvinceDto {

    /**
     * @type {string}
     * @memberof ProvinceDto
     */
    id: string;

    /**
     * @type {Date}
     * @memberof ProvinceDto
     */
    createdAt: Date;

    /**
     * @type {Date}
     * @memberof ProvinceDto
     */
    updatedAt: Date;

    /**
     * @type {string}
     * @memberof ProvinceDto
     */
    title: string;

    /**
     * @type {Array<CityDto>}
     * @memberof ProvinceDto
     */
    cities?: Array<CityDto>;
}
