/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ProductDto } from './product-dto';
import { UserDto } from './user-dto';
 /**
 * 
 *
 * @export
 * @interface RatingDto
 */
export interface RatingDto {

    /**
     * @type {string}
     * @memberof RatingDto
     */
    id: string;

    /**
     * @type {Date}
     * @memberof RatingDto
     */
    createdAt: Date;

    /**
     * @type {Date}
     * @memberof RatingDto
     */
    updatedAt: Date;

    /**
     * @type {string}
     * @memberof RatingDto
     */
    rate: RatingDtoRateEnum;

    /**
     * @type {ProductDto}
     * @memberof RatingDto
     */
    product: ProductDto;

    /**
     * @type {string}
     * @memberof RatingDto
     */
    productId: string;

    /**
     * @type {string}
     * @memberof RatingDto
     */
    userId: string;

    /**
     * @type {UserDto}
     * @memberof RatingDto
     */
    user: UserDto;
}

/**
 * @export
 * @enum {string}
 */
export enum RatingDtoRateEnum {
    _0 = '0',
    _1 = '1',
    _2 = '2',
    _3 = '3',
    _4 = '4',
    _5 = '5'
}

