/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CoordinatesTypeDto } from './coordinates-type-dto';
import { CreateAddressDto } from './create-address-dto';
 /**
 * 
 *
 * @export
 * @interface RegisterVendorDto
 */
export interface RegisterVendorDto {

    /**
     * @type {string}
     * @memberof RegisterVendorDto
     */
    title: string;

    /**
     * @type {string}
     * @memberof RegisterVendorDto
     */
    otherLincenseTitle: string;

    /**
     * @type {Blob}
     * @memberof RegisterVendorDto
     */
    idCard: Blob;

    /**
     * @type {Blob}
     * @memberof RegisterVendorDto
     */
    businessLicense: Blob;

    /**
     * @type {Blob}
     * @memberof RegisterVendorDto
     */
    otherLicense: Blob;

    /**
     * @type {string}
     * @memberof RegisterVendorDto
     */
    natinoalCode: string;

    /**
     * @type {string}
     * @memberof RegisterVendorDto
     */
    telephone: string;

    /**
     * @type {string}
     * @memberof RegisterVendorDto
     */
    mobile: string;

    /**
     * @type {CoordinatesTypeDto}
     * @memberof RegisterVendorDto
     */
    coordinates: CoordinatesTypeDto;

    /**
     * @type {string}
     * @memberof RegisterVendorDto
     */
    supplierId?: string;

    /**
     * @type {string}
     * @memberof RegisterVendorDto
     */
    categoryId: string;

    /**
     * @type {Array<CreateAddressDto>}
     * @memberof RegisterVendorDto
     */
    addresses: Array<CreateAddressDto>;
}
