/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface RuleDto
 */
export interface RuleDto {
  /**
   * @type {string}
   * @memberof RuleDto
   */
  id: string;

  /**
   * @type {Date}
   * @memberof RuleDto
   */
  createdAt: Date;

  /**
   * @type {Date}
   * @memberof RuleDto
   */
  updatedAt: Date;

  /**
   * @type {string}
   * @memberof RuleDto
   */
  title: string;

  /**
   * @type {any}
   * @memberof RuleDto
   */
  rules: string[];

  /**
   * @type {Date}
   * @memberof RuleDto
   */
  deletedAt?: Date;
}
