/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface SettingDto
 */
export interface SettingDto {

    /**
     * @type {string}
     * @memberof SettingDto
     */
    id: string;

    /**
     * @type {Date}
     * @memberof SettingDto
     */
    createdAt: Date;

    /**
     * @type {Date}
     * @memberof SettingDto
     */
    updatedAt: Date;

    /**
     * @type {string}
     * @memberof SettingDto
     */
    key: SettingDtoKeyEnum;

    /**
     * @type {any}
     * @memberof SettingDto
     */
    value: any;

    /**
     * @type {Date}
     * @memberof SettingDto
     */
    deletedAt?: Date;
}

/**
 * @export
 * @enum {string}
 */
export enum SettingDtoKeyEnum {
    SHIPPING = 'SHIPPING'
}

