/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ShipmentInfoDto
 */
export interface ShipmentInfoDto {

    /**
     * @type {string}
     * @memberof ShipmentInfoDto
     */
    time: string;

    /**
     * @type {string}
     * @memberof ShipmentInfoDto
     */
    type: ShipmentInfoDtoTypeEnum;

    /**
     * @type {number}
     * @memberof ShipmentInfoDto
     */
    price: number;
}

/**
 * @export
 * @enum {string}
 */
export enum ShipmentInfoDtoTypeEnum {
    CUSTOMER = 'CUSTOMER',
    VENDOR = 'VENDOR'
}

