/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CategoryDto } from './category-dto';
import { SupplierDto } from './supplier-dto';
import { VendorDto } from './vendor-dto';
 /**
 * 
 *
 * @export
 * @interface SupplierRequestDto
 */
export interface SupplierRequestDto {

    /**
     * @type {string}
     * @memberof SupplierRequestDto
     */
    id: string;

    /**
     * @type {Date}
     * @memberof SupplierRequestDto
     */
    createdAt: Date;

    /**
     * @type {Date}
     * @memberof SupplierRequestDto
     */
    updatedAt: Date;

    /**
     * @type {SupplierDto}
     * @memberof SupplierRequestDto
     */
    supplier: SupplierDto;

    /**
     * @type {VendorDto}
     * @memberof SupplierRequestDto
     */
    vendor: VendorDto;

    /**
     * @type {Array<CategoryDto>}
     * @memberof SupplierRequestDto
     */
    categories: Array<CategoryDto>;
}
