/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface SupplierDto
 */
export interface SupplierDto {

    /**
     * @type {string}
     * @memberof SupplierDto
     */
    id: string;

    /**
     * @type {Date}
     * @memberof SupplierDto
     */
    createdAt: Date;

    /**
     * @type {Date}
     * @memberof SupplierDto
     */
    updatedAt: Date;

    /**
     * @type {string}
     * @memberof SupplierDto
     */
    title: string;
}
