/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TicketChatDto } from './ticket-chat-dto';
import { UserDto } from './user-dto';
 /**
 * 
 *
 * @export
 * @interface TicketDto
 */
export interface TicketDto {

    /**
     * @type {string}
     * @memberof TicketDto
     */
    id: string;

    /**
     * @type {Date}
     * @memberof TicketDto
     */
    createdAt: Date;

    /**
     * @type {Date}
     * @memberof TicketDto
     */
    updatedAt: Date;

    /**
     * @type {string}
     * @memberof TicketDto
     */
    title: string;

    /**
     * @type {UserDto}
     * @memberof TicketDto
     */
    userOne: UserDto;

    /**
     * @type {string}
     * @memberof TicketDto
     */
    userOneId: string;

    /**
     * @type {UserDto}
     * @memberof TicketDto
     */
    userTwo: UserDto;

    /**
     * @type {string}
     * @memberof TicketDto
     */
    userTwoId: string;

    /**
     * @type {string}
     * @memberof TicketDto
     */
    logo: string;

    /**
     * @type {Array<TicketChatDto>}
     * @memberof TicketDto
     */
    ticketChats: Array<TicketChatDto>;
}
