/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TicketEntity } from './ticket-entity';
import { UserDto } from './user-dto';
 /**
 * 
 *
 * @export
 * @interface TicketChatDto
 */
export interface TicketChatDto {

    /**
     * @type {string}
     * @memberof TicketChatDto
     */
    id: string;

    /**
     * @type {Date}
     * @memberof TicketChatDto
     */
    createdAt: Date;

    /**
     * @type {Date}
     * @memberof TicketChatDto
     */
    updatedAt: Date;

    /**
     * @type {string}
     * @memberof TicketChatDto
     */
    text: string;

    /**
     * @type {UserDto}
     * @memberof TicketChatDto
     */
    createdBy: UserDto;

    /**
     * @type {string}
     * @memberof TicketChatDto
     */
    createdById: string;

    /**
     * @type {string}
     * @memberof TicketChatDto
     */
    status: string;

    /**
     * @type {string}
     * @memberof TicketChatDto
     */
    ticketId: string;

    /**
     * @type {TicketEntity}
     * @memberof TicketChatDto
     */
    ticket: TicketEntity;
}
