/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateUserDto
 */
export interface UpdateUserDto {

    /**
     * @type {Blob}
     * @memberof UpdateUserDto
     */
    avatar?: Blob;

    /**
     * @type {string}
     * @memberof UpdateUserDto
     */
    fullName?: string;

    /**
     * @type {string}
     * @memberof UpdateUserDto
     */
    natinoalCode?: string;

    /**
     * @type {string}
     * @memberof UpdateUserDto
     */
    email?: string;
}
