/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AddressDto } from './address-dto';
import { CategoryDto } from './category-dto';
import { CoordinatesTypeDto } from './coordinates-type-dto';
import { LicenseFileType } from './license-file-type';
import { SupplierRequestDto } from './supplier-request-dto';
import { UserDto } from './user-dto';
import { VendorOrderDto } from './vendor-order-dto';
import { VendorProductDto } from './vendor-product-dto';
import { VendorSupplierDto } from './vendor-supplier-dto';
 /**
 * 
 *
 * @export
 * @interface VendorDto
 */
export interface VendorDto {

    /**
     * @type {string}
     * @memberof VendorDto
     */
    id: string;

    /**
     * @type {Date}
     * @memberof VendorDto
     */
    createdAt: Date;

    /**
     * @type {Date}
     * @memberof VendorDto
     */
    updatedAt: Date;

    /**
     * @type {string}
     * @memberof VendorDto
     */
    title: string;

    /**
     * @type {string}
     * @memberof VendorDto
     */
    natinoalCode: string;

    /**
     * @type {string}
     * @memberof VendorDto
     */
    telephone: string;

    /**
     * @type {string}
     * @memberof VendorDto
     */
    mobile: string;

    /**
     * @type {CoordinatesTypeDto}
     * @memberof VendorDto
     */
    coordinates: CoordinatesTypeDto;

    /**
     * @type {string}
     * @memberof VendorDto
     */
    idCardImage: string;

    /**
     * @type {string}
     * @memberof VendorDto
     */
    businessLicense: string;

    /**
     * @type {LicenseFileType}
     * @memberof VendorDto
     */
    otherLincense: LicenseFileType;

    /**
     * @type {string}
     * @memberof VendorDto
     */
    status: VendorDtoStatusEnum;

    /**
     * @type {UserDto}
     * @memberof VendorDto
     */
    user: UserDto;

    /**
     * @type {string}
     * @memberof VendorDto
     */
    userId: string;

    /**
     * @type {SupplierRequestDto}
     * @memberof VendorDto
     */
    request: SupplierRequestDto;

    /**
     * @type {Array<AddressDto>}
     * @memberof VendorDto
     */
    addresses?: Array<AddressDto>;

    /**
     * @type {Array<VendorProductDto>}
     * @memberof VendorDto
     */
    vendorProducts: Array<VendorProductDto>;

    /**
     * @type {VendorSupplierDto}
     * @memberof VendorDto
     */
    vendorSupplier: VendorSupplierDto;

    /**
     * @type {CategoryDto}
     * @memberof VendorDto
     */
    category: CategoryDto;

    /**
     * @type {Array<VendorOrderDto>}
     * @memberof VendorDto
     */
    vendorOrders?: Array<VendorOrderDto>;

    /**
     * @type {number}
     * @memberof VendorDto
     */
    balance: number;

    /**
     * @type {string}
     * @memberof VendorDto
     */
    requestId: string;

    /**
     * @type {string}
     * @memberof VendorDto
     */
    categoryId: string;
}

/**
 * @export
 * @enum {string}
 */
export enum VendorDtoStatusEnum {
    Accepted = 'accepted',
    Pending = 'pending',
    Rejected = 'rejected',
    Deactive = 'deactive'
}

