/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ProductDto } from './product-dto';
import { ShipmentInfoDto } from './shipment-info-dto';
import { SupplierDto } from './supplier-dto';
import { VendorDto } from './vendor-dto';
 /**
 * 
 *
 * @export
 * @interface VendorProductDto
 */
export interface VendorProductDto {

    /**
     * @type {string}
     * @memberof VendorProductDto
     */
    id: string;

    /**
     * @type {Date}
     * @memberof VendorProductDto
     */
    createdAt: Date;

    /**
     * @type {Date}
     * @memberof VendorProductDto
     */
    updatedAt: Date;

    /**
     * @type {string}
     * @memberof VendorProductDto
     */
    saleType?: VendorProductDtoSaleTypeEnum;

    /**
     * @type {SupplierDto}
     * @memberof VendorProductDto
     */
    supplier: SupplierDto;

    /**
     * @type {VendorDto}
     * @memberof VendorProductDto
     */
    vendor: VendorDto;

    /**
     * @type {ProductDto}
     * @memberof VendorProductDto
     */
    product: ProductDto;

    /**
     * @type {string}
     * @memberof VendorProductDto
     */
    vendorId: string;

    /**
     * @type {string}
     * @memberof VendorProductDto
     */
    productId: string;

    /**
     * @type {number}
     * @memberof VendorProductDto
     */
    price: number;

    /**
     * @type {number}
     * @memberof VendorProductDto
     */
    sale?: number;

    /**
     * @type {number}
     * @memberof VendorProductDto
     */
    quantity: number;

    /**
     * @type {string}
     * @memberof VendorProductDto
     */
    supplierId: string;

    /**
     * @type {number}
     * @memberof VendorProductDto
     */
    supplierPrice: number;

    /**
     * @type {string}
     * @memberof VendorProductDto
     */
    summery?: string;

    /**
     * @type {number}
     * @memberof VendorProductDto
     */
    weight?: number;

    /**
     * @type {string}
     * @memberof VendorProductDto
     */
    dimensions?: string;

    /**
     * @type {ShipmentInfoDto}
     * @memberof VendorProductDto
     */
    shipmentInfo: ShipmentInfoDto;

    /**
     * @type {Array<any>}
     * @memberof VendorProductDto
     */
    features?: Array<any>;

    /**
     * @type {string}
     * @memberof VendorProductDto
     */
    color: string;

    /**
     * @type {string}
     * @memberof VendorProductDto
     */
    isActive: string;

    /**
     * @type {Date}
     * @memberof VendorProductDto
     */
    deletedAt?: Date;
}

/**
 * @export
 * @enum {string}
 */
export enum VendorProductDtoSaleTypeEnum {
    PERCENTAGE = 'PERCENTAGE',
    AMOUNT = 'AMOUNT'
}

