/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { OrderDto } from './order-dto';
import { VendorDto } from './vendor-dto';
 /**
 * 
 *
 * @export
 * @interface VendorOrderDto
 */
export interface VendorOrderDto {

    /**
     * @type {string}
     * @memberof VendorOrderDto
     */
    id: string;

    /**
     * @type {Date}
     * @memberof VendorOrderDto
     */
    createdAt: Date;

    /**
     * @type {Date}
     * @memberof VendorOrderDto
     */
    updatedAt: Date;

    /**
     * @type {OrderDto}
     * @memberof VendorOrderDto
     */
    order: OrderDto;

    /**
     * @type {VendorDto}
     * @memberof VendorOrderDto
     */
    vendor?: VendorDto;

    /**
     * @type {string}
     * @memberof VendorOrderDto
     */
    orderId: string;

    /**
     * @type {string}
     * @memberof VendorOrderDto
     */
    vendorId?: string;
}
